version: '2'
services:
    fortniteapi-app:
        image: fortniteapi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fortniteapi-mysql:3306/fortniteapi?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fortniteapi-mysql:
        extends:
            file: mysql.yml
            service: fortniteapi-mysql
